apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: assignment-client-poc
  labels:
    foo: assignment-client
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        foo: assignment-client
    spec:
      containers:
      - name: assignment-client
        image: highfidelity/assignement-client:v0.76.0
        command: ["/usr/local/bin/assignment-client", "-a", "kitchen.highfidelity.io"]
      restartPolicy: Always
